---
- name: configuration setup
  hosts: QA
  become: yes
 

  tasks:
  - name: install tomcat
    apt: 
      name: tomcat9
      state: present
    when: ansible_distribution == "Centos"
  - name: install tomcat
    apt:
      name: tomcat9
      state: present
    when: ansible_distribution == "Ubuntu"

